In [1]:
import numpy as np

In [14]:
test_array = np.array([1,4,5,8],dtype=np.float64)

In [5]:
type(test_array[1])

numpy.float64

In [8]:
test_array.dtype

dtype('float64')

In [7]:
test_array.shape

(4,)

In [10]:
test_array.ndim

1

In [15]:
test_array.nbytes

32

In [16]:
test_array1 = np.array([1,4,5,8],dtype=np.float32)

In [17]:
test_array1.nbytes

16

In [4]:
test_array = np.array([[1,2,3,4],[2,3,4,5]],dtype=np.float64)

In [6]:
test_array.size

8

In [8]:
test_array.shape

(2, 4)

In [9]:
test_array.ndim

2

In [12]:
test_array.reshape(4,-1)

array([[1., 2.],
       [3., 4.],
       [2., 3.],
       [4., 5.]])

In [15]:
test_array.reshape(1,-1)

array([[1., 2., 3., 4., 2., 3., 4., 5.]])

In [16]:
test_array.reshape(2,2,2)

array([[[1., 2.],
        [3., 4.]],

       [[2., 3.],
        [4., 5.]]])

In [18]:
test_array.flatten()

array([1., 2., 3., 4., 2., 3., 4., 5.])

In [19]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
a[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [24]:
test_array[:,::2]

array([[1., 3.],
       [2., 4.]])

In [2]:
a = np.arange(10)

In [6]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.any(a > 5)

True

In [7]:
np.all(a > 5)

False

In [32]:
b = np.repeat(5,10)

In [33]:
b

array([5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [35]:
(a > b).any()

True

In [36]:
(a > b).all()

False

In [13]:
np.logical_and(a > 5, a > 7)

array([False, False, False, False, False, False, False, False,  True,
        True])

In [14]:
np.logical_not(a > 5, a > 7)

array([ True,  True,  True,  True,  True,  True, False, False, False,
       False])

In [15]:
np.logical_or(a > 5, a > 7)

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [39]:
np.where(a > 5, 'TrUe','FaLsE') # where(condition, true, false)

array(['FaLsE', 'FaLsE', 'FaLsE', 'FaLsE', 'FaLsE', 'FaLsE', 'TrUe',
       'TrUe', 'TrUe', 'TrUe'], dtype='<U5')

In [40]:
np.where(a > 5)

(array([6, 7, 8, 9]),)

In [41]:
a = np.array([1, np.NaN, np.Inf],float)

In [43]:
np.isnan(a)

array([False,  True, False])

In [44]:
np.isfinite(a)

array([ True, False, False])

In [52]:
a = np.random.uniform(0,10,10)

In [53]:
a

array([7.81497725, 7.40248809, 1.43309433, 3.87985121, 9.18044989,
       0.10043507, 5.12931319, 3.99741956, 2.78249028, 7.44894974])

In [54]:
np.argmax(a)

4

In [55]:
np.argmin(a)

5

In [56]:
np.argsort(a)

array([5, 2, 8, 3, 7, 6, 1, 9, 0, 4])

In [57]:
a = np.array([np.random.uniform(0,4,3),np.random.uniform(0,4,3),np.random.uniform(0,4,3)])

In [59]:
np.argmax(a,axis=1)

array([2, 0, 2])

In [60]:
np.argmin(a,axis=0)

array([2, 1, 1])

In [63]:
a_int = np.array([np.random.uniform(0,5,4),np.random.uniform(0,5,4)],dtype=int)

In [65]:
np.savetxt('int_data.csv',a_int, delimiter=",")

In [69]:
a = np.loadtxt("int_data.csv")

ValueError: could not convert string to float: '0.000000000000000000e+00,1.000000000000000000e+00,4.000000000000000000e+00,2.000000000000000000e+00'