In [3]:
import numpy as np

In [14]:
test_array = np.array([1,4,5,8],dtype=np.float64)

In [5]:
type(test_array[1])

numpy.float64

In [8]:
test_array.dtype

dtype('float64')

In [7]:
test_array.shape

(4,)

In [10]:
test_array.ndim

1

In [15]:
test_array.nbytes

32

In [16]:
test_array1 = np.array([1,4,5,8],dtype=np.float32)

In [17]:
test_array1.nbytes

16

In [4]:
test_array = np.array([[1,2,3,4],[2,3,4,5]],dtype=np.float64)

In [6]:
test_array.size

8

In [8]:
test_array.shape

(2, 4)

In [9]:
test_array.ndim

2

In [12]:
test_array.reshape(4,-1)

array([[1., 2.],
       [3., 4.],
       [2., 3.],
       [4., 5.]])

In [15]:
test_array.reshape(1,-1)

array([[1., 2., 3., 4., 2., 3., 4., 5.]])

In [16]:
test_array.reshape(2,2,2)

array([[[1., 2.],
        [3., 4.]],

       [[2., 3.],
        [4., 5.]]])

In [18]:
test_array.flatten()

array([1., 2., 3., 4., 2., 3., 4., 5.])

In [19]:
a = np.arange(100).reshape(10,10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [20]:
a[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [24]:
test_array[:,::2]

array([[1., 3.],
       [2., 4.]])